# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ProgressStepViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ProgressStepView', :git => 'https://github.com/gustavoSAS/ProgressStepView.git'

  # Pods for ProgressStepViewDemo

end
